kind: Secret
apiVersion: v1
metadata:
  name: pipelinesvc-pull-secret
  namespace: my-quarkus-app-dev
  uid: c95d2193-ab9e-47b3-99ff-9633d7113c8a
  resourceVersion: '1064873'
  creationTimestamp: '2025-02-20T20:50:36Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2025-02-20T20:50:36Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:.dockerconfigjson': {}
        'f:type': {}
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAicmVnaXN0cnkucmVkaGF0LmlvIjogewogICAgICAgICJhdXRoIjogIk1UTTFPVE0yTnpoOGNHbHdaV3hwYm1WemRtTTZaWGxLYUdKSFkybFBhVXBUVlhwVmVFMXBTamt1WlhsS2VtUlhTV2xQYVVwb1dsUkJNazlIVlRGTlIxWm9Ua1JKTUZwdFRteFpWRlUxVFRKUk1rOUhUbTFOVkdScFRWUk5kMDVEU2prdVRuTnZRMmRUVDJkWFVsOTNaMEpsZGxNMWJVWmlaRTF1WjBwUGJVRkxZVUl5U0VGbVEwTnRSV05PVkRCblNubzNaRFZmUlVWUFpuTnhZWGgxUzNkd1RIRmhVM2hTTmtadWMzQnFkMnhmWDBKelpFdDJRak5WYVZwR2FFTktXVzV5VkdaaGEwZDBYM2RLV0U1NlQwaHZTbGhYVEZKQ1FXNVFNbEp5VTNoeFJHaEhWMUF5Wldjd1dURmZNbVF0UTBjMlNsOXJYM1ZtZDBoeFJrZGxhMU0wVXpSTFNWVlJhVlpzUkZSQ1lrbGZlbGR1VW1kWFEzTjZTRmxGVTJFM1dIa3lhR3hQWjNoQ2RYVjJPR1IyYTIxRkxUZHBSVlpMUmpKNWQwTktTSE5HVkZnMVNUQnBTVkpuTm01dFUwcFFNMFJQY0Y5NVp6bG9OMUp0YVc5Q1RXMXdPSFExVnpkSFlVNUhSeTFGUm5veFFVTTNXRkZYZGtnNWRFRldjMlYzTUhFMFpsbGhNSFZKZVRWVGRuZFRRbEZ2WW1SUFYydFhUSGd4TFhsblZEQlFSMmx4TWkxNFdXbzJhM0J4VmpNd09UVTVaa3BwY1dGSlJIWlNlV0ZWTW1waWVHVnNjbXBxVFVKSFpWRTRkRUpEUVdkRmJFSkRUVzl2WTFKWlRsSkZkVk15T1haR1ZXOUhRazF4YlVaU1gwUlZNRUUyVkRaT1FURk9kVk51V25CVVpGUm1OVzVRVkVKcldXTm5SM2RxYm5ad1RsRnZiMVpyWWtGRFpXNXJTamxQWVZCbGFHdDJPRzVtT1ZCb1dHbDBZV2RhTFdaVFZFNUZWVEptV0VVNVZrRTJRMWxaUVc5ZlZFZDVhbUZTZUdWa01WRllVVmd3WmtOdFJGODRUbkJ3T0ZWeFduaEtibWN4WkVGcVJucGtjbXc1YmpGalNubG9aWGxCYVhoRVdIRk9ZMko2Wm5OcFFVdFRRa2QwVkVaVGIybFlXRXN4Ym1aMVRHOUpjRXhJZFVSclV6bFpNVGRMVDFaWFlYQkVZMnhMYW5KTVV6QmFNVUkxVFZOdVJUUnBWbmcxWVZjMmJtNVRMVGg1UzAxT1RHWkRNRzlYTUVvM2MyRm5Oa3c0ZEc1Wk1rRkpURnBvT0daRlkwWk1NVWwzTkdoVWRqTkJiME14YUV4WWVHZHFObk00ZVhKVU1VUkRjMDFpY3pRPSIKICAgICAgfQogICAgfQogIH0=
type: kubernetes.io/dockerconfigjson
