apiVersion: apps/v1
kind: Deployment
metadata:
  name: faster-whisper-server
  labels:
    app: faster-whisper-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faster-whisper-server
  template:
    metadata:
      labels:
        app: faster-whisper-server
    spec:
      serviceAccountName: sa-with-anyuid
      containers:
      - name: faster-whisper-server
        image: faster-whisper:latest
        ports:
        - containerPort: 8000
        securityContext:
          runAsUser: 1000
        resources:
          limits:
            cpu: "10"
            memory: 20G
          requests:
            cpu: "2"
            memory: 6G
