kind: Secret
apiVersion: v1
metadata:
  name: redhat-na-ssa-tektonpipeline-pull-secret
  namespace: stt
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjbVZrYUdGMFgyNWhYM056WVN0MFpXdDBiMjV3YVhCbGJHbHVaVHBIV0ZreFYxcFJSVEphVWxrMk0wMDBPVFUxTVZWUU0wZENSa3BMU0VnNFQwVk9WVVV5T0ZrNFYwZzFNVWMxTXpCQ05qZE9PRk01VVVSRFdFeFRPVlpDIiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson
