apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stt-stackrox-token
  namespace: stt
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secrets/janusidp/stackrox
        property: token
      secretKey: rox_api_token
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: stt-stackrox-token