kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline
  namespace: stt
secrets:
  - name: pipeline-dockercfg-vjmth
  - name: redhat-na-ssa-tektonpipeline-pull-secret # This secret is for the pipeline robot account to push to quay
imagePullSecrets:
  - name: pipeline-dockercfg-vjmth
