apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: stt-ubi-pipeline
  namespace: stt
spec:
  params:
    - default: 'https://github.com/redhat-na-ssa/whitepaper-stt-evaluation-on-kubernetes.git'
      name: GIT_REPO
      type: string
    - default: ./pipeline/ubi/Dockerfile
      name: DOCKERFILE_LOCATION
      type: string
    - default: 'central-stackrox.apps.cluster-qk89t.qk89t.sandbox40.opentlc.com:443'
      name: stackrox-endpoint
      type: string
    - default: stt-stackrox-token
      name: stackrox-secret
      type: string
    - default: quay.io/redhat_na_ssa/sttubi
      name: OUTPUT_IMAGE
      type: string
    - default: 'http://rekor-server.trusted-artifact-signer.svc'
      name: rekor-url
      type: string
  results:
    - description: The common vulnerabilities and exposures (CVE) result
      name: ACS_SCAN_OUTPUT
      value: $(tasks.acs-image-scan.results.SCAN_OUTPUT)
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: main
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: 'registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:dd5c8d08d52e304a542921634ebe6b5ff3d63c5f68f6d644e88417859b173ec8'
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source_dir
    - name: build-image-with-sbom
      params:
        - name: IMAGE
          value: $(params.OUTPUT_IMAGE)
        - name: DOCKERFILE
          value: $(params.DOCKERFILE_LOCATION)
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: build-image
      workspaces:
        - name: source
          workspace: source_dir
    - name: acs-image-scan
      params:
        - name: rox_central_endpoint
          value: $(params.stackrox-endpoint)
        - name: rox_api_token
          value: $(params.stackrox-secret)
        - name: image
          value: $(params.OUTPUT_IMAGE)
        - name: insecure-skip-tls-verify
          value: 'true'
      runAfter:
        - build-image-with-sbom
      taskRef:
        kind: Task
        name: acs-image-scan-with-vulnerability
      workspaces:
        - name: reports
          workspace: reports
    - name: acs-image-check
      params:
        - name: rox_central_endpoint
          value: $(params.stackrox-endpoint)
        - name: rox_api_token
          value: $(params.stackrox-secret)
        - name: image
          value: $(params.OUTPUT_IMAGE)
        - name: insecure-skip-tls-verify
          value: 'true'
      runAfter:
        - acs-image-scan
      taskRef:
        kind: Task
        name: acs-image-check
      workspaces:
        - name: reports
          workspace: reports
    - name: upload-sbom-to-tpa
      params:
        - name: COMPONENT_ID
          value: stt-ubi
      runAfter:
        - acs-image-check
      taskRef:
        kind: Task
        name: upload-sbom-to-tpa
      workspaces:
        - name: sboms
          workspace: source_dir
    - name: query-rekor-signed-provenance
      params:
        - name: imageDigest
          value: $(tasks.build-image-with-sbom.results.IMAGE_DIGEST)
        - name: rekorUrl
          value: $(params.rekor-url)
      runAfter:
        - upload-sbom-to-tpa
      taskRef:
        kind: Task
        name: rekor-signed-provenance
  workspaces:
    - name: source_dir
    - name: reports
