kind: Secret
apiVersion: v1
metadata:
  name: redhat-na-ssa-tektonpipeline-pull-secret
  namespace: stt
data:
  .dockerconfigjson: <<DOCKER CONFIG JSON FROM QUAY ACCOUNT>>
type: kubernetes.io/dockerconfigjson
